apiVersion: v1
kind: ConfigMap
metadata:
  name: blog-nginx-config
  namespace: default
data:
  default.conf: |
    server {
        listen 80;
        server_name _;
        root /usr/share/nginx/html;
        index index.html;

        # Enable gzip compression
        gzip on;
        gzip_vary on;
        gzip_min_length 1000;
        gzip_proxied any;
        gzip_types text/plain text/css text/xml application/xml application/javascript application/json application/rss+xml;
        gzip_disable "msie6";

        # Use Nginx's default error handling
        # No custom error_page directive needed

        # Force trailing slash for directories
        rewrite ^([^.]*[^/])$ $1/ permanent;

        # Security headers
        add_header X-Content-Type-Options "nosniff";
        add_header X-Frame-Options "SAMEORIGIN";
        add_header X-XSS-Protection "1; mode=block";

        # Cache control for static assets
        location ~* \.(jpg|jpeg|png|gif|ico|css|js)$ {
            expires 30d;
            add_header Cache-Control "public, max-age=2592000";
        }

        # Try to serve file directly, fallback to 404
        location / {
            try_files $uri $uri/ =404;
        }

        error_page 404 /404.html;
    }
