apiVersion: v1
kind: Endpoints
metadata:
  name: home-assistant
  namespace: default
  labels:
    app.kubernetes.io/instance: home-assistant
    app.kubernetes.io/name: home-assistant
subsets:
  - addresses:
      - ip: homeassistant.local
    ports:
      - port: 8123
        name: http
        protocol: TCP
