apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: home-assistant
  namespace: default
  labels:
    app.kubernetes.io/instance: home-assistant
    app.kubernetes.io/name: home-assistant
    kubernetes.io/service-name: home-assistant
addressType: FQDN
ports:
  - name: http
    port: 8123
    protocol: TCP
endpoints:
  - addresses:
      - homeassistant.local
