apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: home-assistant-websocket
  namespace: default
spec:
  headers:
    customRequestHeaders:
      Upgrade: "websocket"
      Connection: "Upgrade"
    customResponseHeaders:
      Upgrade: "websocket"
      Connection: "Upgrade"
