apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: first-pool
spec:
  blocks:
    - start: 192.168.2.65
      stop: 192.168.2.70
    - start: 192.168.2.20
      stop: 192.168.2.30