apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: arc-controller
  namespace: arc-systems
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gha-rs-controller
      app.kubernetes.io/instance: arc
