apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: arc-runners
  namespace: arc-runners
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/component: runner
      app.kubernetes.io/instance: arc-runner-set
