apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: arc-listener
  namespace: arc-systems
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/component: runner-scale-set-listener
      app.kubernetes.io/instance: arc-runner-set
