apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: velero-b2-credentials
  namespace: velero
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: velero-b2-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        cloud: |
          [default]
          aws_access_key_id={{ .AWS_ACCESS_KEY_ID }}
          aws_secret_access_key={{ .AWS_SECRET_ACCESS_KEY }}
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: prod-backup-b2-access-key-id
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: prod-backup-b2-secret-access-key
