apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - helmrepo.yaml
  - external-secret.yaml
  - release.yaml
  - pdb-velero.yaml
  - networkpolicy-default.yaml
  - snapshot-crd-volumesnapshotclasses.yaml
  - snapshot-crd-volumesnapshotcontents.yaml
  - snapshot-crd-volumesnapshots.yaml
  - snapshot-controller-rbac.yaml
  - snapshot-controller.yaml
  - volume-snapshot-class.yaml

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/managed-by: flux
      app.kubernetes.io/part-of: velero
