apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: velero
  namespace: velero
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: velero
      app.kubernetes.io/instance: velero
