apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: pvc-full-daily
  namespace: velero
spec:
  schedule: "0 3 * * *"
  template:
    ttl: 336h0m0s
    storageLocation: default
    includedNamespaces:
      - '*'
    excludedNamespaces:
      - arc-runners
    snapshotVolumes: true
    defaultVolumesToFsBackup: true
    includeClusterResources: true
---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: pvc-full-weekly-archive
  namespace: velero
spec:
  schedule: "0 4 * * 0"
  template:
    ttl: 2160h0m0s
    storageLocation: default
    includedNamespaces:
      - '*'
    excludedNamespaces:
      - arc-runners
    snapshotVolumes: true
    defaultVolumesToFsBackup: true
    includeClusterResources: true
