apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-backup-b2-credentials
  namespace: postgresql-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: cnpg-backup-b2-credentials
    creationPolicy: Owner
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: prod-backup-b2-access-key-id
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: prod-backup-b2-secret-access-key
