apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - blog.yaml
  - cert-practice.yaml
  - home-assistant.yaml
  - mealie.yaml
  - mosquitto.yaml
  - n8n.yaml
  - zigbee2mqtt.yaml
