apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 1h
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: longhorn
      version: "1.9.x"
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  values:
    defaultSettings:
      defaultDataPath: /var/mnt/longhorn
      createDefaultDiskLabeledNodes: true
      replicaSoftAntiAffinity: false
      replicaZoneSoftAntiAffinity: true
      defaultReplicaCount: 2
    persistence:
      defaultClass: false
      defaultClassReplicaCount: 2
