apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-secrets-store-provider-azure
  namespace: kube-system
spec:
  interval: 1h
  chart:
    spec:
      chart: csi-secrets-store-provider-azure
      version: "1.4.x"
      sourceRef:
        kind: HelmRepository
        name: azure-marketplace
        namespace: flux-system