apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 10m
  chart:
    spec:
      chart: external-secrets
      version: "0.20.3"
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  values:
    installCRDs: false
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 256Mi
    certController:
      resources:
        requests:
          cpu: 25m
          memory: 64Mi
        limits:
          cpu: 150m
          memory: 192Mi
    webhook:
      resources:
        requests:
          cpu: 25m
          memory: 64Mi
        limits:
          cpu: 150m
          memory: 192Mi
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              namespace: external-secrets
              name: external-secrets
            patch: |
              - op: add
                path: /spec/template/spec/containers/0/resources
                value:
                  requests:
                    cpu: 50m
                    memory: 128Mi
                  limits:
                    cpu: 250m
                    memory: 256Mi
          - target:
              kind: Deployment
              namespace: external-secrets
              name: external-secrets-cert-controller
            patch: |
              - op: add
                path: /spec/template/spec/containers/0/resources
                value:
                  requests:
                    cpu: 25m
                    memory: 64Mi
                  limits:
                    cpu: 150m
                    memory: 192Mi
          - target:
              kind: Deployment
              namespace: external-secrets
              name: external-secrets-webhook
            patch: |
              - op: add
                path: /spec/template/spec/containers/0/resources
                value:
                  requests:
                    cpu: 25m
                    memory: 64Mi
                  limits:
                    cpu: 150m
                    memory: 192Mi
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
