apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backup-config
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: backup-config
    creationPolicy: Owner
  data:
    - secretKey: B2_BUCKET_NAME
      remoteRef:
        key: prod-backup-b2-bucket-name
    - secretKey: B2_REGION
      remoteRef:
        key: prod-backup-b2-region
    - secretKey: B2_S3_URL
      remoteRef:
        key: prod-backup-b2-s3-url
