apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 10m
  chart:
    spec:
      chart: traefik
      version: "40.3.0"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
  values:
    global:
      checkNewVersion: false
      sendAnonymousUsage: false
    additionalArguments:
      - --serversTransport.insecureSkipVerify=true
      - --log.level=INFO
    podSecurityContext:
      seccompProfile:
        type: RuntimeDefault
    deployment:
      enabled: true
      replicas: 3
      podAnnotations: {}
      additionalContainers: []
      initContainers: []
      annotations: {}
    rbac:
      enabled: true
    service:
      type: LoadBalancer
      enabled: true
      single: true
      spec: {}
      labels: {}
      # annotations:
      #   lbipam.cilium.io/ips: 192.168.2.68
      annotationsTCP:
        lbipam.cilium.io/ips: 192.168.2.68
      annotationsUDP:
        lbipam.cilium.io/ips: 192.168.2.68
      externalIPs: []
      loadBalancerSourceRanges: []
    ports:
      web:
        http:
          redirections:
            entryPoint:
              to: websecure
              scheme: https
              permanent: true
      websecure:
        exposedPort: 443
        expose:
          default: true
        http:
          tls:
            enabled: true
        http3:
          enabled: true
          advertisedPort: 443
    providers:
      kubernetesCRD:
        enabled: true
        allowExternalNameServices: true
      kubernetesIngress:
        enabled: true
        publishedService:
          enabled: false
        allowExternalNameServices: true
    ingressRoute:
      dashboard:
        enabled: true
  install:
    crds: Create
    timeout: 2m
  upgrade:
    crds: CreateReplace
    timeout: 2m
