kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: unifi-controller-data
  namespace: unifi
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
  storageClassName: proxmox-csi
  volumeName: pvc-ec6a28f9-8b1f-4312-84f7-8b53dbc6f0c5 
