apiVersion: v1
kind: ConfigMap
metadata:
  name: apple-health-lake-cloudflared-config
  namespace: default
data:
  config.yaml: |
    tunnel: 3cc18bfc-9a4c-4c9d-91bd-e886420d5f4b
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    ingress:
      - hostname: health-lake.siemons-it.nl
        service: http://apple-health-lake.default.svc.cluster.local:80
      - hostname: health-lake-mcp.siemons-it.nl
        service: http://apple-health-lake-mcp.default.svc.cluster.local:80
      - service: http_status:404
