apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: apple-health-lake-secrets
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: apple-health-lake-secrets
    creationPolicy: Owner
  data:
    - secretKey: API_KEY
      remoteRef:
        key: prod-apple-health-lake-api-key
