apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: apple-health-lake-cloudflared-credentials
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: apple-health-lake-cloudflared-credentials
    creationPolicy: Owner
  data:
    - secretKey: credentials.json
      remoteRef:
        key: prod-apple-health-lake-cloudflare-credentials
