apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: apple-health-lake-cloudflared-token
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: apple-health-lake-cloudflared-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: prod-apple-health-lake-cloudflare-key
