apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: apple-health-lake
  namespace: default
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: apple-health-lake
      app.kubernetes.io/instance: apple-health-lake
      app.kubernetes.io/component: ingester
