apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-os-pvc
  namespace: unifi-os
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: proxmox-csi
  resources:
    requests:
      storage: 16Gi
