apiVersion: v1
kind: Service
metadata:
  name: unifi-os-service
  namespace: unifi-os
  labels:
    app.kubernetes.io/instance: unifi-os-server
    app.kubernetes.io/name: unifi-os-server
  annotations:
    service.cilium.io/global: "true"
    service.cilium.io/shared: "true"
    io.cilium/lb-ipam-ips: "192.168.2.21"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/instance: unifi-os-server
    app.kubernetes.io/name: unifi-os-server
  ports:
    - name: webui
      port: 443
      targetPort: webui
      protocol: TCP
    - name: communication
      port: 8080
      targetPort: communication
      protocol: TCP
    - name: network-app
      port: 8443
      targetPort: network-app
      protocol: TCP
    - name: hotspot-secure
      port: 8444
      targetPort: hotspot-secure
      protocol: TCP
    - name: hotspot-redir0
      port: 8880
      targetPort: hotspot-redir0
      protocol: TCP
    - name: hotspot-redir1
      port: 8881
      targetPort: hotspot-redir1
      protocol: TCP
    - name: hotspot-redir2
      port: 8882
      targetPort: hotspot-redir2
      protocol: TCP
    - name: stun
      port: 3478
      targetPort: stun
      protocol: UDP
    - name: rtp
      port: 5005
      targetPort: rtp
      protocol: TCP
    - name: syslog
      port: 5514
      targetPort: syslog
      protocol: UDP
    - name: aqmps
      port: 5671
      targetPort: aqmps
      protocol: TCP
    - name: mobile-speed
      port: 6789
      targetPort: mobile-speed
      protocol: TCP
    - name: id-hub
      port: 9543
      targetPort: id-hub
      protocol: TCP
    - name: discovery
      port: 10003
      targetPort: discovery
      protocol: UDP
    - name: site-super
      port: 11084
      targetPort: site-super
      protocol: TCP
