apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-pushover
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: alertmanager-pushover
    creationPolicy: Owner
  data:
    - secretKey: user-key
      remoteRef:
        key: pushover-user-key
    - secretKey: app-token
      remoteRef:
        key: pushover-app-token
