{
 "title": "Velero cluster view",
 "tags": [ "velero" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(velero_backup_success_total{job=\"integrations/velero\"}, job)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(velero_backup_success_total{job=\"integrations/velero\",job=~\"$job\"}, cluster)"
   },
   {
    "name": "top_cluster_count",
    "label": "Top cluster count",
    "query": "2 : 2,4 : 4,6 : 6,8 : 8,10 : 10"
   }
  ]
 },
 "panels": [
  {
   "title": "Successful backups / $__interval ",
   "type": "stat",
   "description": "Number of successful backups across all clusters.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cluster) ((increase(velero_backup_success_total{job=~\"$job\",cluster=~\"$cluster\"}[$__interval:])))",
     "legendFormat": "Backups"
    }
   ]
  },
  {
   "title": "Failed backups / $__interval ",
   "type": "stat",
   "description": "Number of failed backups across all clusters",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cluster) ((increase(velero_backup_failure_total{job=~\"$job\",cluster=~\"$cluster\"}[$__interval:])))",
     "legendFormat": "Backups"
    }
   ]
  },
  {
   "title": "Succesful restores / $__interval ",
   "type": "stat",
   "description": "Number of succesful restores across all clusters.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cluster) ((increase(velero_restore_success_total{job=~\"$job\",cluster=~\"$cluster\"}[$__interval:])))",
     "legendFormat": "Restores"
    }
   ]
  },
  {
   "title": "Failed restores / $__interval ",
   "type": "stat",
   "description": "Number of failed restores across all clusters.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cluster) ((increase(velero_restore_failed_total{job=~\"$job\",cluster=~\"$cluster\"}[$__interval:])))",
     "legendFormat": "Restores"
    }
   ]
  },
  {
   "title": "Velero alerts",
   "type": "alertlist",
   "description": "Status of firing alerts for Velero.",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 }
  },
  {
   "title": "Top clusters by backups / $__interval ",
   "type": "timeseries",
   "description": "The top clusters by number of backups.\n",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "topk by(cluster)($top_cluster_count, sum by (cluster) (increase(velero_backup_success_total{job=~\"$job\",cluster=~\"$cluster\"}[$__interval:])))",
     "legendFormat": "{{cluster}} - success"
    },
    {
     "expr": "topk by(cluster)($top_cluster_count, sum by (cluster) (increase(velero_backup_failure_total{job=~\"$job\",cluster=~\"$cluster\"}[$__interval:])))",
     "legendFormat": "{{cluster}} - failure"
    },
    {
     "expr": "topk by(cluster)($top_cluster_count, sum by (cluster) (increase(velero_backup_attempt_total{job=~\"$job\",cluster=~\"$cluster\"}[$__interval:])))",
     "legendFormat": "{{cluster}} - attempt"
    }
   ]
  },
  {
   "title": "Top clusters by restores / $__interval ",
   "type": "timeseries",
   "description": "Top clusters by number of restores.\n",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "topk by(cluster)($top_cluster_count, sum by (cluster) (increase(velero_restore_success_total{job=~\"$job\",cluster=~\"$cluster\"}[$__interval:])))",
     "legendFormat": "{{cluster}} - success"
    },
    {
     "expr": "topk by(cluster)($top_cluster_count, sum by (cluster) (increase(velero_restore_failed_total{job=~\"$job\",cluster=~\"$cluster\"}[$__interval:])))",
     "legendFormat": "{{cluster}} - failure"
    },
    {
     "expr": "topk by(cluster)($top_cluster_count, sum by (cluster) (increase(velero_restore_success_total{job=~\"$job\",cluster=~\"$cluster\"}[$__interval:])))",
     "legendFormat": "{{cluster}} - attempt"
    }
   ]
  },
  {
   "title": "Top clusters by backup size",
   "type": "timeseries",
   "description": "Top clusters by size of backups.\n",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk by(cluster)($top_cluster_count, sum by (cluster) (velero_backup_tarball_size_bytes{job=~\"$job\",cluster=~\"$cluster\"}))",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Top clusters by volume snapshots / $__interval ",
   "type": "timeseries",
   "description": "Top clusters by number of volume snapshots.\n",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "topk by(cluster)($top_cluster_count, sum by (cluster) (increase(velero_volume_snapshot_success_total{job=~\"$job\",cluster=~\"$cluster\"}[$__interval:])))",
     "legendFormat": "{{cluster}} - success"
    },
    {
     "expr": "topk by(cluster)($top_cluster_count, sum by (cluster) (increase(velero_volume_snapshot_failure_total{job=~\"$job\",cluster=~\"$cluster\"}[$__interval:])))",
     "legendFormat": "{{cluster}} - failure"
    },
    {
     "expr": "topk by(cluster)($top_cluster_count, sum by (cluster) (increase(velero_volume_snapshot_attempt_total{job=~\"$job\",cluster=~\"$cluster\"}[$__interval:])))",
     "legendFormat": "{{cluster}} - attempt"
    }
   ]
  },
  {
   "title": "Top clusters by CSI snapshots / $__interval ",
   "type": "timeseries",
   "description": "Top clusters by number of CSI snapshots.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "topk by(cluster)($top_cluster_count, sum by (cluster) (increase(velero_csi_snapshot_success_total{job=~\"$job\",cluster=~\"$cluster\"}[$__interval:])))",
     "legendFormat": "{{cluster}} - success"
    },
    {
     "expr": "topk by(cluster)($top_cluster_count, sum by (cluster) (increase(velero_csi_snapshot_failure_total{job=~\"$job\",cluster=~\"$cluster\"}[$__interval:])))",
     "legendFormat": "{{cluster}} - failure"
    },
    {
     "expr": "topk by(cluster)($top_cluster_count, sum by (cluster) (increase(velero_csi_snapshot_attempt_total{job=~\"$job\",cluster=~\"$cluster\"}[$__interval:])))",
     "legendFormat": "{{cluster}} - attempt"
    }
   ]
  }
 ]
}
{
 "title": "Velero logs",
 "tags": [ "velero" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values({job=\"integrations/velero\"}, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values({job=\"integrations/velero\",job=~\"$job\"}, instance)"
   },
   {
    "name": "level",
    "label": "Level",
    "query": "label_values({job=\"integrations/velero\",job=~\"$job\",instance=~\"$instance\"}, level)"
   },
   { "name": "regex_search", "label": "Regex search" },
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Logs volume",
   "type": "timeseries",
   "description": "Logs volume grouped by \"level\" label.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (level) (count_over_time({job=\"integrations/velero\",job=~\"$job\",instance=~\"$instance\",level=~\"$level\"}\n|~ \"$regex_search\"\n\n[$__auto]))\n",
     "legendFormat": "{{ level }}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{job=\"integrations/velero\",job=~\"$job\",instance=~\"$instance\",level=~\"$level\"} \n|~ \"$regex_search\"\n\n\n"
    }
   ]
  }
 ]
}
{
 "title": "Velero overview",
 "tags": [ "velero" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(velero_backup_attempt_total{}, job)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(velero_backup_attempt_total{job=~\"$job\"}, cluster)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(velero_backup_attempt_total{}, instance)"
   },
   {
    "name": "schedule",
    "label": "Schedule",
    "query": "label_values(velero_backup_attempt_total{job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}, schedule)"
   }
  ]
 },
 "panels": [
  {
   "title": "Backup success rate (1 hour)",
   "type": "gauge",
   "description": "Success rate of backups within the instance in the past hour.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (instance) (label_replace(increase(velero_backup_success_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}[1h]), \"schedule\", \"none\", \"schedule\", \"^$\") / label_replace(increase(velero_backup_attempt_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}[1h]), \"schedule\", \"none\", \"schedule\", \"^$\") >  0)",
     "legendFormat": "{{schedule}}"
    }
   ]
  },
  {
   "title": "Restore success rate (1 hour)",
   "type": "gauge",
   "description": "Success rate of restores within the instance in the past hour.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (instance) (label_replace(increase(velero_restore_success_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}[1h]), \"schedule\", \"none\", \"schedule\", \"^$\") / label_replace(increase(velero_restore_attempt_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}[1h]), \"schedule\", \"none\", \"schedule\", \"^$\") >  0)",
     "legendFormat": "{{schedule}}"
    }
   ]
  },
  {
   "title": "Successful backups / $__interval ",
   "type": "stat",
   "description": "Number of successful backups.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(velero_backup_success_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}[$__interval:]))",
     "legendFormat": "Backups"
    }
   ]
  },
  {
   "title": "Failed backups / $__interval ",
   "type": "stat",
   "description": "Number of failed backups.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(velero_backup_failure_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}[$__interval:]))",
     "legendFormat": "Backups"
    }
   ]
  },
  {
   "title": "Restore validation failure / $__interval ",
   "type": "stat",
   "description": "Number of failed restore validations.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(label_replace(velero_restore_validation_failed_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}, \"schedule\", \"none\", \"schedule\", \"^$\")[$__interval:]))",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": "Backup validation failure / $__interval ",
   "type": "stat",
   "description": "Number of failed backup validations.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(label_replace(velero_backup_validation_failure_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}, \"schedule\", \"none\", \"schedule\", \"^$\")[$__interval:]))",
     "legendFormat": "failure"
    }
   ]
  },
  { "title": "Backup", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 24, "y": 4 } },
  {
   "title": "Backup count / $__interval ",
   "type": "timeseries",
   "description": "Number of failed and successful backups.\n",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "increase(label_replace(velero_backup_success_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}, \"schedule\", \"none\", \"schedule\", \"^$\")[$__interval:])",
     "legendFormat": "{{schedule}} - success"
    },
    {
     "expr": "increase(label_replace(velero_backup_failure_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}, \"schedule\", \"none\", \"schedule\", \"^$\")[$__interval:])",
     "legendFormat": "{{schedule}} - failure"
    },
    {
     "expr": "increase(label_replace(velero_backup_attempt_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}, \"schedule\", \"none\", \"schedule\", \"^$\")[$__interval:])",
     "legendFormat": "{{schedule}} - attempt"
    }
   ]
  },
  {
   "title": "Backup success rate / $__interval",
   "type": "timeseries",
   "description": "Success rate of backups.\n",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "increase(label_replace(velero_backup_success_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}, \"schedule\", \"none\", \"schedule\", \"^$\")[$__rate_interval:]) / clamp_min(rate(label_replace(velero_backup_attempt_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}, \"schedule\", \"none\", \"schedule\", \"^$\")[$__rate_interval:]),1)",
     "legendFormat": "{{schedule}}"
    }
   ]
  },
  {
   "title": "Backup size",
   "type": "timeseries",
   "description": "Size of backups for this clusters given schedule.\n",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "label_replace(velero_backup_tarball_size_bytes{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}, \"schedule\", \"none\", \"schedule\", \"^$\")",
     "legendFormat": "{{schedule}}"
    }
   ]
  },
  {
   "title": "Backup time",
   "type": "heatmap",
   "description": "The time it took to create backups.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(increase(label_replace(velero_backup_duration_seconds_bucket{le!=\"+Inf\", job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}, \"schedule\", \"none\", \"schedule\", \"^$\")[$__interval:])) by (le)"
    }
   ]
  },
  { "title": "Restore", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 24, "y": 23 } },
  {
   "title": "Restore count / $__interval ",
   "type": "timeseries",
   "description": "Number of failed and successful restores.\n",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "increase(label_replace(velero_restore_success_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}, \"schedule\", \"none\", \"schedule\", \"^$\")[$__interval:])",
     "legendFormat": "{{schedule}} - success"
    },
    {
     "expr": "increase(label_replace(velero_restore_failed_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}, \"schedule\", \"none\", \"schedule\", \"^$\")[$__interval:])",
     "legendFormat": "{{schedule}} - failure"
    },
    {
     "expr": "increase(label_replace(velero_restore_attempt_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}, \"schedule\", \"none\", \"schedule\", \"^$\")[$__interval:])",
     "legendFormat": "{{schedule}} - attempt"
    }
   ]
  },
  {
   "title": "Restore success rate / $__interval",
   "type": "timeseries",
   "description": "Success rate of restores.\n",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "increase(label_replace(velero_restore_success_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}, \"schedule\", \"none\", \"schedule\", \"^$\")[$__interval:]) / clamp_min(increase(label_replace(velero_restore_attempt_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}, \"schedule\", \"none\", \"schedule\", \"^$\")[$__interval:]),1)",
     "legendFormat": "{{schedule}}"
    }
   ]
  },
  { "title": "CSI snapshots", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 24, "y": 30 } },
  {
   "title": "CSI snapshot count / $__interval ",
   "type": "timeseries",
   "description": "Number of failed and successful CSI snapshots.\n",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum by (schedule) (increase(label_replace(velero_csi_snapshot_success_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}, \"schedule\", \"none\", \"schedule\", \"^$\")[$__interval:]))",
     "legendFormat": "{{schedule}} - success"
    },
    {
     "expr": "sum by (schedule) (increase(label_replace(velero_csi_snapshot_success_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}, \"schedule\", \"none\", \"schedule\", \"^$\")[$__interval:]))",
     "legendFormat": "{{schedule}} - failure"
    },
    {
     "expr": "sum by (schedule) (increase(label_replace(velero_csi_snapshot_attempt_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}, \"schedule\", \"none\", \"schedule\", \"^$\")[$__interval:]))",
     "legendFormat": "{{schedule}} - attempt"
    }
   ]
  },
  {
   "title": "CSI snapshot success rate / $__interval",
   "type": "timeseries",
   "description": "Success rate of CSI snapshots.\n",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (schedule) (increase(label_replace(velero_csi_snapshot_success_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}, \"schedule\", \"none\", \"schedule\", \"^$\")[$__interval:]) / clamp_min(increase(label_replace(velero_csi_snapshot_attempt_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}, \"schedule\", \"none\", \"schedule\", \"^$\")[$__interval:]),1)) ",
     "legendFormat": "{{schedule}}"
    }
   ]
  },
  { "title": "Volume snapshots", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 24, "y": 37 } },
  {
   "title": "Volume snapshot count / $__interval ",
   "type": "timeseries",
   "description": "Number of failed and successful volume snapshots.\n",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "increase(label_replace(velero_volume_snapshot_success_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}, \"schedule\", \"none\", \"schedule\", \"^$\")[$__interval:])",
     "legendFormat": "{{schedule}} - success"
    },
    {
     "expr": "increase(label_replace(velero_volume_snapshot_failure_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}, \"schedule\", \"none\", \"schedule\", \"^$\")[$__interval:])",
     "legendFormat": "{{schedule}} - failure"
    },
    {
     "expr": "increase(label_replace(velero_volume_snapshot_attempt_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}, \"schedule\", \"none\", \"schedule\", \"^$\")[$__interval:])",
     "legendFormat": "{{schedule}} - attempt"
    }
   ]
  },
  {
   "title": "Volume snapshot success rate / $__interval",
   "type": "timeseries",
   "description": "Success rate of volume snapshots.\n",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "increase(label_replace(velero_volume_snapshot_success_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}, \"schedule\", \"none\", \"schedule\", \"^$\")[$__interval:]) / clamp_min(increase(label_replace(velero_volume_snapshot_attempt_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}, \"schedule\", \"none\", \"schedule\", \"^$\")[$__interval:]),1)",
     "legendFormat": "{{schedule}}"
    }
   ]
  }
 ]
}