apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 1h
  chart:
    spec:
      chart: kube-prometheus-stack
      version: ">=60.0.0 <70.0.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Service
              namespace: monitoring
              name: kube-prometheus-stack-alertmanager
            patch: |
              - op: replace
                path: /spec/ports/0/targetPort
                value: http-web
          - target:
              kind: Service
              namespace: monitoring
              name: kube-prometheus-stack-grafana
            patch: |
              - op: replace
                path: /spec/ports/0/targetPort
                value: grafana
          - target:
              kind: Service
              namespace: monitoring
              name: kube-prometheus-stack-prometheus
            patch: |
              - op: replace
                path: /spec/ports/0/targetPort
                value: http-web
          - target:
              kind: Service
              namespace: monitoring
              name: kube-prometheus-stack-kube-state-metrics
            patch: |
              - op: replace
                path: /spec/ports/0/targetPort
                value: http
          - target:
              kind: Service
              namespace: monitoring
              name: kube-prometheus-stack-prometheus-node-exporter
            patch: |
              - op: replace
                path: /spec/ports/0/targetPort
                value: http-metrics
          - target:
              kind: Service
              namespace: kube-system
              name: kube-prometheus-stack-coredns
            patch: |
              - op: replace
                path: /spec/ports/0/targetPort
                value: metrics
          - target:
              kind: DaemonSet
              namespace: monitoring
              name: kube-prometheus-stack-prometheus-node-exporter
            patch: |
              - op: replace
                path: /spec/template/spec/containers/0/resources
                value:
                  requests:
                    cpu: 25m
                    memory: 64Mi
                  limits:
                    cpu: 200m
                    memory: 256Mi
          - target:
              kind: ServiceAccount
              namespace: monitoring
              name: kube-prometheus-stack-alertmanager
            patch: |
              - op: add
                path: /automountServiceAccountToken
                value: false
          - target:
              kind: ServiceAccount
              namespace: monitoring
              name: kube-prometheus-stack-grafana
            patch: |
              - op: add
                path: /automountServiceAccountToken
                value: false
          - target:
              kind: Deployment
              namespace: monitoring
              name: kube-prometheus-stack-grafana
            patch: |
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: kube-prometheus-stack-grafana
                namespace: monitoring
              spec:
                template:
                  spec:
                    initContainers:
                      - name: init-chown-data
                        resources:
                          requests:
                            cpu: 10m
                            memory: 64Mi
                          limits:
                            cpu: 100m
                            memory: 128Mi
                    containers:
                      - name: grafana
                        resources:
                          requests:
                            cpu: 100m
                            memory: 256Mi
                          limits:
                            cpu: 500m
                            memory: 512Mi
                      - name: grafana-sc-dashboard
                        resources:
                          requests:
                            cpu: 10m
                            memory: 64Mi
                          limits:
                            cpu: 100m
                            memory: 128Mi
                      - name: grafana-sc-datasources
                        resources:
                          requests:
                            cpu: 10m
                            memory: 64Mi
                          limits:
                            cpu: 100m
                            memory: 128Mi
          - target:
              kind: Deployment
              namespace: monitoring
              name: kube-prometheus-stack-kube-state-metrics
            patch: |
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: kube-prometheus-stack-kube-state-metrics
                namespace: monitoring
              spec:
                template:
                  spec:
                    containers:
                      - name: kube-state-metrics
                        resources:
                          requests:
                            cpu: 50m
                            memory: 128Mi
                          limits:
                            cpu: 300m
                            memory: 384Mi
          - target:
              kind: Deployment
              namespace: monitoring
              name: kube-prometheus-stack-operator
            patch: |
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: kube-prometheus-stack-operator
                namespace: monitoring
              spec:
                template:
                  spec:
                    containers:
                      - name: kube-prometheus-stack
                        resources:
                          requests:
                            cpu: 100m
                            memory: 256Mi
                          limits:
                            cpu: 500m
                            memory: 512Mi
  values:
    prometheusOperator:
      prometheusConfigReloader:
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
    kubeControllerManager:
      enabled: false
    kubeEtcd:
      enabled: false
    kubeProxy:
      enabled: false
    kubeScheduler:
      enabled: false
    alertmanager:
      alertmanagerSpec:
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
      ingress:
        enabled: true
        ingressClassName: traefik
        annotations:
          cert-manager.io/cluster-issuer: local-siemons-it-nl
        hosts:
          - alertmanager.local.siemons-it.nl
        tls:
          - secretName: local-siemons-it-nl-tls
            hosts:
              - alertmanager.local.siemons-it.nl
    grafana:
      sidecar:
        dashboards:
          enabled: true
          label: grafana_dashboard
          labelValue: "1"
          searchNamespace: monitoring
      ingress:
        enabled: true
        ingressClassName: traefik
        annotations:
          cert-manager.io/cluster-issuer: local-siemons-it-nl
        hosts:
          - grafana.local.siemons-it.nl
        tls:
          - secretName: local-siemons-it-nl-tls
            hosts:
              - grafana.local.siemons-it.nl
      persistence:
        enabled: true
        storageClassName: proxmox-csi
        accessModes:
          - ReadWriteOnce
        size: 5Gi
    prometheus:
      ingress:
        enabled: true
        ingressClassName: traefik
        annotations:
          cert-manager.io/cluster-issuer: local-siemons-it-nl
        hosts:
          - prom.local.siemons-it.nl
        tls:
          - secretName: local-siemons-it-nl-tls
            hosts:
              - prom.local.siemons-it.nl
      prometheusSpec:
        resources:
          requests:
            cpu: 200m
            memory: 1Gi
          limits:
            cpu: "1"
            memory: 2Gi
        retention: 10d
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: proxmox-csi
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 20Gi
