apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - helmrepo.yaml
  - helmrelease.yaml
  - servicemonitor-velero.yaml
  - podmonitor-cnpg.yaml
  - prometheusrule-backups.yaml
  - grafana-dashboard-backups.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/managed-by: flux
      app.kubernetes.io/part-of: monitoring
