apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cert-practice-postgres
  namespace: postgresql-system
spec:
  instances: 2  # temporarily 2: only 2 nodes have nvme-k8s storage right now (work-02 removed). Bump back to 3 once pve2 gets its own nvme-k8s pool.
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          cnpg.io/cluster: cert-practice-postgres
  backup:
    barmanObjectStore:
      destinationPath: s3://homelab-backups-prod/cnpg/cert-practice-postgres
      endpointURL: https://s3.eu-central-003.backblazeb2.com
      s3Credentials:
        accessKeyId:
          name: cnpg-backup-b2-credentials
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: cnpg-backup-b2-credentials
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
        maxParallel: 4
      data:
        compression: gzip
    retentionPolicy: "14d"
  storage:
    size: 5Gi
    storageClass: proxmox-csi-nvme
  bootstrap:
    initdb:
      database: cert_practice
      owner: certpractice
