apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: n8n-postgres
  namespace: postgresql-system
spec:
  instances: 3  # temporarily 3 during migration to Longhorn: the 3rd (new) instance lands on the longhorn storageClass, then we drop one of the two old proxmox-csi-nvme instances and scale back to 2.
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          cnpg.io/cluster: n8n-postgres
  backup:
    barmanObjectStore:
      destinationPath: s3://homelab-backups-prod/cnpg/n8n-postgres
      endpointURL: https://s3.eu-central-003.backblazeb2.com
      s3Credentials:
        accessKeyId:
          name: cnpg-backup-b2-credentials
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: cnpg-backup-b2-credentials
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
        maxParallel: 4
      data:
        compression: gzip
    retentionPolicy: "14d"
  storage:
    size: 10Gi
    storageClass: longhorn
  bootstrap:
    initdb:
      database: n8n
      owner: n8n

