apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-host
  namespace: n8n
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: n8n-host
    creationPolicy: Owner
  data:
    - secretKey: N8N_HOST
      remoteRef:
        key: prod-n8n-host