apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: n8n-postgres-app
  namespace: n8n
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: n8n-postgres-app
    creationPolicy: Owner
  data:
    - secretKey: DB_USER
      remoteRef:
        key: prod-n8n-db-user
    - secretKey: DB_PASSWORD
      remoteRef:
        key: prod-n8n-db-password
    - secretKey: DB_NAME
      remoteRef:
        key: n8n
