apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: n8n-webhook-url
  namespace: n8n
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: n8n-webhook-url
    creationPolicy: Owner
  data:
    - secretKey: WEBHOOK_URL
      remoteRef:
        key: prod-n8n-webhook-url