apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-data-longhorn
  namespace: n8n
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
  volumeMode: Filesystem
