apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-data-longhorn
  namespace: n8n
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
  volumeMode: Filesystem
