apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mealie
  namespace: default
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: mealie
      app.kubernetes.io/instance: mealie
