kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mealie-api-data-longhorn
  namespace: default
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: 1Gi
  storageClassName: "longhorn"
