apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cert-manager-repo
      version: v1.17.1
  interval: 1m0s
  values:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    cainjector:
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 250m
          memory: 256Mi
    webhook:
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 250m
          memory: 256Mi
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Service
              namespace: cert-manager
              name: cert-manager
            patch: |
              - op: replace
                path: /spec/ports/0/targetPort
                value: http-metrics
          - target:
              kind: Service
              namespace: cert-manager
              name: cert-manager-cainjector
            patch: |
              - op: replace
                path: /spec/ports/0/targetPort
                value: http-metrics
          - target:
              kind: Deployment
              namespace: cert-manager
              name: cert-manager
            patch: |
              - op: add
                path: /spec/template/spec/containers/0/resources
                value:
                  requests:
                    cpu: 100m
                    memory: 256Mi
                  limits:
                    cpu: 500m
                    memory: 512Mi
          - target:
              kind: Deployment
              namespace: cert-manager
              name: cert-manager-cainjector
            patch: |
              - op: add
                path: /spec/template/spec/containers/0/resources
                value:
                  requests:
                    cpu: 50m
                    memory: 128Mi
                  limits:
                    cpu: 250m
                    memory: 256Mi
          - target:
              kind: Deployment
              namespace: cert-manager
              name: cert-manager-webhook
            patch: |
              - op: add
                path: /spec/template/spec/containers/0/resources
                value:
                  requests:
                    cpu: 50m
                    memory: 128Mi
                  limits:
                    cpu: 250m
                    memory: 256Mi
