apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
- namespace.yaml
- helmrepo.yaml
- cert-manager.crds.yaml
- helmrelease.yaml
- issuers/
- certificates/

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/managed-by: flux
    app.kubernetes.io/part-of: cert-manager
