apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgresql-system

resources:
  - namespace.yaml
  - helm-repository.yaml
  - release.yaml
  - databases/n8n.yaml

commonLabels:
  app.kubernetes.io/part-of: cloudnative-pg
  app.kubernetes.io/managed-by: flux