apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: postgresql-system
spec:
  interval: 5m
  chart:
    spec:
      chart: cloudnative-pg
      version: "0.18.x"
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
        namespace: postgresql-system