apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zigbee2mqtt-mqtt-credentials
  namespace: default
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: zigbee2mqtt-mqtt-credentials
    creationPolicy: Owner
  data:
  - secretKey: mqtt-user
    remoteRef:
      key: zigbee2mqtt-mqtt-user
  - secretKey: mqtt-password
    remoteRef:
      key: zigbee2mqtt-mqtt-password