kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zigbee2mqtt-claim-longhorn
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
