kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zigbee2mqtt-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: proxmox-csi-nvme
  resources:
    requests:
      storage: 1Gi