apiVersion: v1
kind: ConfigMap
metadata:
  name: bridge-conf
  namespace: default
data:
  mosquitto.conf: |
    listener 1883
    allow_anonymous true

    connection broker0
    address mosquitto-p.default
    topic # both 0 