apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - bridge.yaml
  - deployment.yaml
  - deployment2.yaml
  - service.yaml
  - service2.yaml

configMapGenerator:
  - name: mosquitto-0-conf
    namespace: default
    files:
      - config/mosquitto-0.conf
  - name: mosquitto-1-conf
    namespace: default
    files:
      - config/mosquitto-1.conf