apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: default
  annotations:
    "lbipam.cilium.io/ips": "192.168.2.67"
spec:
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
    - name: wss
      port: 9001
      targetPort: 9001
  selector:
    app: mosquitto
  type: LoadBalancer
  #externalTrafficPolicy: Local
  # Use an loadBalancerIP (e.g. MetalLB) or externalIP depending on your setup