apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: proxmox-csi-plugin-node
  namespace: csi-proxmox
  labels:
    app.kubernetes.io/component: node
    app.kubernetes.io/instance: proxmox-csi-plugin
    app.kubernetes.io/name: proxmox-csi-plugin
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: node
      app.kubernetes.io/instance: proxmox-csi-plugin
      app.kubernetes.io/name: proxmox-csi-plugin
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/component: node
        app.kubernetes.io/instance: proxmox-csi-plugin
        app.kubernetes.io/name: proxmox-csi-plugin
    spec:
      enableServiceLinks: false
      priorityClassName: system-node-critical
      serviceAccountName: proxmox-csi-plugin-node
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      tolerations:
        - key: node.kubernetes.io/unschedulable
          operator: Exists
          effect: NoSchedule
        - key: node.kubernetes.io/disk-pressure
          operator: Exists
          effect: NoSchedule
      containers:
        - name: proxmox-csi-plugin-node
          image: ghcr.io/sergelogvinov/proxmox-csi-node:v0.18.1
          imagePullPolicy: IfNotPresent
          args:
            - -v=5
            - --csi-address=unix:///csi/csi.sock
            - --node-id=$(NODE_NAME)
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 300m
              memory: 384Mi
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
                - CHOWN
                - DAC_OVERRIDE
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: socket
              mountPath: /csi
            - name: kubelet
              mountPath: /var/lib/kubelet
              mountPropagation: Bidirectional
            - name: dev
              mountPath: /dev
            - name: sys
              mountPath: /sys
        - name: csi-node-driver-registrar
          image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.9.4
          imagePullPolicy: IfNotPresent
          args:
            - -v=5
            - --csi-address=unix:///csi/csi.sock
            - --kubelet-registration-path=/var/lib/kubelet/plugins/csi.proxmox.sinextra.dev/csi.sock
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: socket
              mountPath: /csi
            - name: registration
              mountPath: /registration
        - name: liveness-probe
          image: registry.k8s.io/sig-storage/livenessprobe:v2.11.0
          imagePullPolicy: IfNotPresent
          args:
            - -v=5
            - --csi-address=unix:///csi/csi.sock
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: socket
              mountPath: /csi
      volumes:
        - name: socket
          hostPath:
            path: /var/lib/kubelet/plugins/csi.proxmox.sinextra.dev/
            type: DirectoryOrCreate
        - name: registration
          hostPath:
            path: /var/lib/kubelet/plugins_registry/
            type: Directory
        - name: kubelet
          hostPath:
            path: /var/lib/kubelet
            type: Directory
        - name: dev
          hostPath:
            path: /dev
            type: Directory
        - name: sys
          hostPath:
            path: /sys
            type: Directory