apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clawdbot-config
  namespace: clawdbot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: proxmox-csi
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clawdbot-workspace
  namespace: clawdbot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: proxmox-csi
  volumeMode: Filesystem
